### ISSUE TITLE
一键登录 登录失败

### ISSUE THREAD

**Issue by lawvs** [Matataki-io/Fan-TaskBoard#16]
## 复现

![screenshot](https://user-images.githubusercontent.com/18554747/109152577-08780e80-77af-11eb-810c-461831275a26.gif)

## Console

![image](https://user-images.githubusercontent.com/18554747/109152516-f5653e80-77ae-11eb-9f94-29a56ce8267c.png)

## Network

![image](https://user-images.githubusercontent.com/18554747/109152778-4d9c4080-77af-11eb-8aa0-288271dfeb67.png)

## Code

https://github.com/Matataki-io/Fan-TaskBoard/blob/3caa5bce067062adf488c0632872329818c010f6/src/views/Oauth/index.tsx#L27-L45

其中 `await setCookieService({ accessToken })` 返回了正确的结果

```json
{"code":0,"data":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.qPDaXYT32g9aAtpuYXEcKX7VpFf4RXhkY7LhEkfRIiM"}
```

但是 `initUser()` 的 `await getUserProfile()` 却返回了空对象 `{}`

**Comment by xiaotiandada** [comment]
谢谢反馈

我这边没有复现这个问题 您尝试换浏览器使用 如果还是一样的错误可以继续留言讨论

可以留下您的Matataki用户主页地址一起排查问题所在

**Comment by xiaotiandada** [comment]
> ## 复现
> ![screenshot](https://user-images.githubusercontent.com/18554747/109152577-08780e80-77af-11eb-810c-461831275a26.gif)
> 
> ## Console
> ![image](https://user-images.githubusercontent.com/18554747/109152516-f5653e80-77ae-11eb-9f94-29a56ce8267c.png)
> 
> ## Network
> ![image](https://user-images.githubusercontent.com/18554747/109152778-4d9c4080-77af-11eb-8aa0-288271dfeb67.png)
> 
> ## Code
> https://github.com/Matataki-io/Fan-TaskBoard/blob/3caa5bce067062adf488c0632872329818c010f6/src/views/Oauth/index.tsx#L27-L45
> 
> 其中 `await setCookieService({ accessToken })` 返回了正确的结果
> 
> ```json
> {"code":0,"data":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.XXXXXXXXXXXXXXXXXXXXXXXXXXXX.qPDaXYT32g9aAtpuYXEcKX7VpFf4RXhkY7LhEkfRIiM"}
> ```
> 
> 但是 `initUser()` 的 `await getUserProfile()` 却返回了空对象 `{}`

谢谢反馈

我这边没有复现这个问题 您尝试换浏览器使用 如果还是一样的错误可以继续留言讨论

可以留下您的Matataki用户主页地址一起排查问题所在

**Comment by xiaotiandada** [comment]
可能是因为禁用了第三方Cookie 请检查浏览器设置

**Comment by billchenchina** [comment]
允许第三方 Cookie 方法：
Chrome 用户：chrome://settings/cookies 调整至”Block third-party cookies in Incognito“或”Allow all cookies“
Firefox 用户：about:preferences#privacy 调整至”Standard“

**Comment by lawvs** [comment]
![image](https://user-images.githubusercontent.com/18554747/109167927-a8d72e80-77c1-11eb-809f-03697a62606a.png)

点击 `Site not working` 允许第三方 Cookie 之后登录成功。非常感谢！

**Comment by xiaotiandada** [comment]
目前最新的Safari默认会阻止第三方Cookie需要开启

[在 Mac 上的 Safari 浏览器中管理 Cookie 和网站数据](https://support.apple.com/zh-cn/guide/safari/sfri11471/mac)
